Repository TheAlgorithms/Solidity, pull requests merged in 2022-10, with the labels that each got.

#31 fix: remove Foundry extension ` is Test` from contract
  src/Sorts/BubbleSort.sol
Labels: bug

#38 Create QuickSort.sol
  src/Sorts/QuickSort.sol
Labels: enhancement

#45 Change for issue#39 fix
  src/Searches/BinarySearch.sol
Labels: invalid

#49 chore: add codeowners
  .github/CODEOWNERS
Labels: enhancement

#46 fix: add new entry + fix list display
  README.md
Labels: documentation

#56 [Doc]: Update the list alphabetically + fix `Searches` folder ref
  README.md
  src/DynamicProgramming/Knapsack.sol
  src/DynamicProgramming/test/Knapsack.t.sol
  src/Maths/BinaryExponentiation.sol
Labels: documentation

#54 [add] reverse array function
  src/Maths/ReverseArray.sol
  src/Maths/test/ReverseArray.t.sol
Labels: enhancement

#48 Changes to use markdown formating. issue #2
  src/Maths/Abs.sol
  src/Maths/AddArray.sol
  src/Maths/AliquotSum.sol
  src/Maths/Area.sol
  src/Maths/AverageMean.sol
  src/Maths/MulArray.sol
  src/Maths/Percentage.sol
  src/Maths/ReverseArray.sol
  src/Maths/armstrongNumber.sol
  src/Maths/factorial.sol
  src/Maths/fibonacci.sol
  src/Maths/lucasSeries.sol
  src/Maths/stringMatch.sol
  src/Maths/volume.sol
  src/Maths/zellersCongruenceAlgorithm.sol
  src/Searches/BinarySearch.sol
  src/Sorts/BubbleSort.sol
  src/Sorts/MergeSort.sol
  src/Sorts/QuickSort.sol
  src/Sorts/SelectionSort.sol
Labels: documentation

#62 fix: AutoPrettier changes not being pushed
  .github/workflows/autoprettier.yml
  package-lock.json
  src/Maths/Abs.sol
  src/Maths/AddArray.sol
  src/Maths/AliquotSum.sol
  src/Maths/Area.sol
  src/Maths/AverageMean.sol
  src/Maths/BinaryExponentiation.sol
  src/Maths/MulArray.sol
  src/Maths/Percentage.sol
  src/Maths/ReverseArray.sol
  src/Maths/armstrongNumber.sol
  src/Maths/factorial.sol
  src/Maths/fibonacci.sol
  src/Maths/lucasSeries.sol
  src/Maths/stringMatch.sol
  src/Maths/test/BinaryExponentiation.sol
  src/Maths/test/ReverseArray.t.sol
  src/Maths/volume.sol
  src/Maths/zellersCongruenceAlgorithm.sol
  src/Searches/BinarySearch.sol
  src/Searches/LinearSearch.sol
  src/Sorts/BubbleSort.sol
  src/Sorts/MergeSort.sol
  src/Sorts/QuickSort.sol
  src/Sorts/SelectionSort.sol
  src/Sorts/test/MergeSort.sol
Labels: bug
